# Fish shell configuration.
# The `.local` file at the bottom is auto-generated by `dotfile bootstrap`
# and sources the right OS/profile variants (e.g. config.macos.fish,
# config.work.fish) for the active machine.

set -gx EDITOR vim
set -gx LANG en_US.UTF-8

# Dotfiles on PATH
set -gx DOTFILES "$HOME/dotfiles"
fish_add_path "$DOTFILES/scripts"
fish_add_path "$HOME/.local/bin"

# Git aliases
alias gs 'git status'
alias gd 'git diff'
alias gc 'git commit'
alias gl 'git log --oneline --graph --decorate -20'

# OS/profile variants (config.macos.fish, config.work.fish, …) are
# sourced through this .local file, regenerated on every bootstrap.
test -e ~/.config/fish/config.fish.local; and source ~/.config/fish/config.fish.local
