name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write  # trusted publishing

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v8.1.0

      - run: uv build

      - uses: pypa/gh-action-pypi-publish@release/v1
